### ISSUE TITLE
Thanks! 

### ISSUE THREAD

**Issue by Kyris-Fey-Butenneig** [dPhoeniixx/Textnow-API#1]
I don't know how to comment so I am going to leave it here. 

My issue? You are too amazing. You just saved me hours of work, and I want to thank you for that. Thanks a lot, dude.

**Comment by dPhoeniixx** [comment]
I am very happy because I gave you something that helped you
you made my day by this issue <3

**Comment by dPhoeniixx** [comment]
I am very happy
you made my day by this issue <3
