### ISSUE TITLE
TextNow make message read.

### ISSUE THREAD

**Issue by diashkhan** [dPhoeniixx/Textnow-API#4]
You have done a great work to be honest, just Awesome. Can you please add an extra piece of coding which will make a particular text from unread to read. Thank you in advance!

**Comment by blacksector** [comment]
@diashkhan 
I added my own function inside of textnow.py and it looks like this:
```python
def messageRead(self, msg):
  if self.Login == False:
          return False

  contactValue = msg["contact_value"]
  msgId = msg["id"]

  node = 'users/%s/conversations/%s'%(self.username, contactValue)
  query = '?client_type=TN_ANDROID&client_id=%s&latest_message_id=%s'%(self.Login, msgId)

  msgData = OrderedDict([
          ('read', True)
          ])
  jsonData = self.genJson(msgData)
  sign = self.genSignature("PATCH", node, query+jsonData)
  req = self.sendReq("PATCH", "%s%s%s"%(self.API_URL, node, query), sign, jsonData)

  return req
```

when you call it from your main program call it like this:

```python
TN = textnow.Textnow(EMAIL, PASSWORD)
TN.login()
TN.messageRead(x)
```
the variable `x` is a single element from the TN.getMessages()["messages"]. Here is a sample of how it looks:
```python
{u'username': u'<REDACTED>', u'e164_contact_value': u'<REDACTED>', u'contact_type': 2, u'read': True, u'message': u"Hello World", u'message_direction': 2, u'conversation_filtering': {u'first_time_contact': False, u'previous_number_owner_contact': None}, u'date': u'2018-02-09T18:20:20Z', u'contact_name': u'', u'message_type': 1, u'id': 20087166090L, u'contact_value': u'<REDACTED>'}
```

Some more sample code to make it work in case I wasn't entirely clear:

```python

TN = textnow.Textnow(EMAIL, PASSWORD)
TN.login()


# Last known message id
lastMessageId = 1

while True:
    try:
        messages = TN.getMessages(lastMessageId)
        # Iterate through messages from response
        for x in messages["messages"]:
            # Unread and incoming message:
            if x["read"] == False and x["message_direction"] == 1:
                # Mark message as read.
                TN.messageRead(x)

                number = str(x["e164_contact_value"])
                
                print "Message from " + number

            # Set last message id - this is sort of a pagination mechanism
            lastMessageId = int(x["id"])

    except:
        print "Something went wrong! :("
```

The function `TN.messageRead()` doesn't return anything valuable or of use. I haven't exactly made it so that it is user friendly and didn't think I would have been releasing it. So modify it to your own use case.

**Comment by diashkhan** [comment]
thank you so much! you are awesome :D

**Comment by blacksector** [comment]
@diashkhan happy to help 😄

**Comment by sookah** [comment]
@blacksector How did you reverse engineer the routes for the android?  I was wondering if i can extend the api for requesting new phonenumber.

**Comment by blacksector** [comment]
@sookah never reverse engineered anything. Simply took a look at the requests being sent and received and simply played around with it until I was able to tell the TextNow API that the message has been "seen".

If you are trying to request a new phone number I would try to take a look at the requests being sent by the web app when registering a new number. For instance, open up a new account on textnow and request a new phone number. Keep the google chrome or whatever browser console open and keep an eye on the requests being sent to the TextNow server, it might shed some light on how they do it. Sorry I am not longer using this project so I couldn't help you :\
