### ISSUE TITLE
Can not send message text with slashes in it

### ISSUE THREAD

**Issue by shivangparikh** [dPhoeniixx/Textnow-API#5]
Hey,
First of all awesome work on this :)
I just came across this issue and cant get workaround for this, it would be great if you can figure it out..
I tried to send message text "hello test site is http://testsite.com/" and it does not work and sendMessage method response is below

> {'error_code': 'SIGNATURE_INVALID'}

but when I remove slashes "hello test site is http:testsite.com" it works !
I think something to do with genSignature which generate signature containing message text 

Your help will be highly appreciated :)
Have a good one :+1:

**Comment by buidoi8x** [comment]
Hello shivangparikh
Could you send  any messages to another textnow number ?
I use this script but it got error.
I am finding a script what could send message from textnow.
I want to send message to my phone number textnow don't get delete.
![loi](https://user-images.githubusercontent.com/27664184/37092177-5b6931e8-223d-11e8-9df0-c00d4dc54d00.png)

**Comment by dPhoeniixx** [comment]
fixed
https://github.com/dPhoeniixx/Textnow-API/commit/86f4fd0f97b184e8f60b7e63084f72bd53f846fc

**Comment by shivangparikh** [comment]
Awesome.. Thank you so much @dPhoeniixx .. Appreciate your work :)
